// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screencast} from '../models';
import {main} from '../models';

export function CancelRecording():Promise<void>;

export function DeleteScreenshot(arg1:string):Promise<void>;

export function GetHomeDir():Promise<string>;

export function GetSavedMicrophone():Promise<string>;

export function GetScreenshotsBaseURL():Promise<string>;

export function GetSystemAudioSupported():Promise<screencast.SystemAudioInfo>;

export function GetVideosDir():Promise<string>;

export function ListMicrophones():Promise<Array<screencast.AudioDevice>>;

export function ListScreenshots():Promise<Array<main.ScreenshotInfo>>;

export function OpenToolsPalette():Promise<void>;

export function PauseRecording():Promise<void>;

export function RenameScreenshot(arg1:string,arg2:string):Promise<void>;

export function ResizeToPalette():Promise<void>;

export function ResizeToSettings():Promise<void>;

export function ResizeToStudio():Promise<void>;

export function ResumeRecording():Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveMicrophone(arg1:string):Promise<void>;

export function SetMicEnabled(arg1:boolean):Promise<void>;

export function SetSystemEnabled(arg1:boolean):Promise<void>;

export function StartRecording(arg1:boolean,arg2:boolean,arg3:string):Promise<string>;

export function StopRecording():Promise<string>;

export function TakeAreaScreenshot():Promise<void>;

export function TakeScreenshot():Promise<void>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
