// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir():Promise<string>;

export function GetScreenshotsBaseURL():Promise<string>;

export function ListScreenshots():Promise<Array<string>>;

export function OpenToolsPalette():Promise<void>;

export function PauseRecording():Promise<void>;

export function ResizeToPalette():Promise<void>;

export function ResizeToStudio():Promise<void>;

export function ResumeRecording():Promise<void>;

export function StartRecording(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function StopRecording():Promise<string>;

export function TakeAreaScreenshot():Promise<void>;

export function TakeScreenshot():Promise<void>;
