// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenToolsPalette():Promise<void>;

export function ResizeToPalette():Promise<void>;

export function ResizeToStudio():Promise<void>;
