// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetScreenshotsBaseURL() {
  return window['go']['main']['App']['GetScreenshotsBaseURL']();
}

export function ListScreenshots() {
  return window['go']['main']['App']['ListScreenshots']();
}

export function OpenToolsPalette() {
  return window['go']['main']['App']['OpenToolsPalette']();
}

export function PauseRecording() {
  return window['go']['main']['App']['PauseRecording']();
}

export function ResizeToPalette() {
  return window['go']['main']['App']['ResizeToPalette']();
}

export function ResizeToStudio() {
  return window['go']['main']['App']['ResizeToStudio']();
}

export function ResumeRecording() {
  return window['go']['main']['App']['ResumeRecording']();
}

export function StartRecording(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TakeAreaScreenshot() {
  return window['go']['main']['App']['TakeAreaScreenshot']();
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}
