// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenToolsPalette() {
  return window['go']['main']['App']['OpenToolsPalette']();
}

export function ResizeToPalette() {
  return window['go']['main']['App']['ResizeToPalette']();
}

export function ResizeToStudio() {
  return window['go']['main']['App']['ResizeToStudio']();
}
